name: Build and push image

on:
#  push:
#    branches: ["main"]
#  pull_request:
#    branches: ["main"]
  workflow_dispatch:

env:
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_DEFAULT_TAG: "latest"
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Image meta
        uses: docker/metadata-action@v5
        id: meta
        with:
          tags: |
            type=raw,value=${{ env.IMAGE_DEFAULT_TAG }}
          labels: |
            org.opencontainers.image.title=${{ env.IMAGE_NAME }}
            org.opencontainers.image.url=${{ github.repositoryUrl }}
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            containers.bootc=1

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_DEFAULT_TAG }}
          oci: false
          containerfiles: |
            ./Dockerfile

      - name: Login to Container Registry
        uses: redhat-actions/podman-login@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Push to Container Registry
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          registry: ${{ env.REGISTRY }}
